# fly.toml app configuration file generated for tailscale-silow on 2023-09-19T15:04:42+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tailscale-silow"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  PORT = "41641"

[[services]]
  internal_port = 41641
  protocol = "udp"

  [[services.ports]]
    handlers = ["tls", "http", "pg_tls"]
    port = "41641"

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75
